sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install: npm install
script: "npm run build"
deploy:
  - provider: s3
    access_key_id: $ENG_AWS_ACCESS_KEY_ID
    secret_access_key: $ENG_AWS_SECRET_ACCESS_KEY
    bucket: "sp-messaging-tools-ui-uat"
    skip_cleanup: true
    local_dir: build
    on:
      branch: develop
      node: "6"
  - provider: s3
    access_key_id: $ENG_AWS_ACCESS_KEY_ID
    secret_access_key: $ENG_AWS_SECRET_ACCESS_KEY
    bucket: "sp-messaging-tools-ui-staging"
    skip_cleanup: true
    local_dir: build
    on:
      branch: master
      node: "6"
