sudo: false
language: node_js
node_js:
  - "6"
env:
  global:
    - CXX=g++-4.8
  matrix:
    - REACT_APP_ENV=staging
    - REACT_APP_ENV=production
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # allows arch specific modules to be built
      - g++-4.8
install: npm install
script: "npm test && npm run build"
deploy:
  - provider: s3
    access_key_id: $ENG_AWS_ACCESS_KEY_ID
    secret_access_key: $ENG_AWS_SECRET_ACCESS_KEY
    bucket: "sp-messaging-tools-ui-staging"
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    local_dir: build
    on:
      branch: master
      condition: $REACT_APP_ENV = staging
      node: "6"
  - provider: s3
    access_key_id: $ENG_AWS_ACCESS_KEY_ID
    secret_access_key: $ENG_AWS_SECRET_ACCESS_KEY
    bucket: "sp-messaging-tools-ui-production"
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    local_dir: build
    on:
      tags: true
      condition: $REACT_APP_ENV = production
      node: "6"
