sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
install: npm install
script: "npm run build"
deploy:
   - provider: s3
     access_key_id: $ENG_AWS_ACCESS_KEY_ID
     secret_access_key: $ENG_AWS_SECRET_ACCESS_KEY
     bucket: "sp-messaging-tools-ui-uat"
     acl: public_read
     region: us-east-1
     skip_cleanup: true
     local_dir: build
     on:
     	branch: develop
   - provider: s3
     access_key_id: $ENG_AWS_ACCESS_KEY_ID
     secret_access_key: $ENG_AWS_SECRET_ACCESS_KEY
     bucket: "sp-messaging-tools-ui-staging"
     acl: public_read
     region: us-east-1
     skip_cleanup: true
     local_dir: build
     on:
     	branch: master
