name: Tools-UI deploy production

on:
  push:
    tags:
      - '*'

jobs:
  build:

    environment: production
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ENG_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ENG_AWS_SECRET_ACCESS_KEY }}
      REACT_APP_ENV: production
      REACT_APP_GTM_ID: ${{ secrets.REACT_APP_GTM_ID }}

    strategy:
      matrix:
        node-version: [10.17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Deploy
      uses: reggionick/s3-deploy@v3 # https://github.com/Reggionick/s3-deploy
      with:
        folder: build
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
